version: '3.7'
services:
 db:
  container_name: timescaledb10
  image: timescale/timescaledb:latest-pg10
  env_file:
      - database.env # configure postgres
  ports:
      - '5010:5432'
  volumes:
      - ./backup:/backup
      - ./data:/var/lib/postgresql/data